# Site settings
title: Travel Blog
email: yuahwen.cheng@gmail.com
description: Treehouse project ref. https://teamtreehouse.com/library/create-a-jekyll-site-on-github
baseurl: "/travel-blog"
#url: ""
twitter_username: a1985256
avatar: "https://pbs.twimg.com/profile_images/619910720008794112/t81GuBaU.jpg" # Set footer avatar - twitter profile image
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Yueh-Wen. Cheng" # Set default author name
      categories: "palces"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
